### PR TITLE
Log click events and set origin level 2

### PR DESCRIPTION
**Pull request by fbeaudoincoveo**
Demo: https://codesandbox.io/s/coveo-headless-react-tsx-material-ui-example-010-forked-su7l4

### CODE REVIEW

**Review by jpmarceau — APPROVED** [review]
works great!

**Review by jgeddes-coveo — APPROVED** [review]
Looks great!

**Review by kaitlynkatz — APPROVED** [review]
This looks good to me, although I don't like having to set originLevel2 ourselves. Should this not be a feature of the Tab controller? If you agree, I can bring it up with the ui-kit team.

**Comment by fbeaudoincoveo** [comment]
> This looks good to me, although I don't like having to set originLevel2 ourselves. Should this not be a feature of the Tab controller? If you agree, I can bring it up with the ui-kit team.

Agreed @kaitlynkatz , I would have expected this to be handled automatically by the Tab controller. Please validate with the Search UI team whether this is actually the intended behavior.

**Pull request merged**
