### PR TITLE
version 0.28.1

### PR DESCRIPTION
**Pull request by dlutzCoveo**

### CODE REVIEW

**Comment by dlutzCoveo** [comment]
I have also update the engine (it doesn't show up as a change in this PR), if you can take a look at that too.
Thanks!

**Comment by kaitlynkatz** [comment]
Can you link the sandbox? I don't see it anywhere on the codesandbox dashboard, maybe it's bc of the new strategy we talked about?

**Comment by dlutzCoveo** [comment]
Here it is: [https://codesandbox.io/s/coveo-headless-0281-t5l8f](url)

**Review by kaitlynkatz — APPROVED** [review]
Works fine! A bunch of comments, but all small stuff:
- the name in the package.json still says the old version
- now that we have all the facets making the page longer, we should adjust the resultsperpage component so that the default number is more than three, and so that the options are more appropriate (maybe 3-5-10 or 5-10-15? whatever looks best)
- we can remove the comment on the breadcrumbs component that says it only shows plain facet breadcrumbs since that's no longer true
- the pager has getters but they're being underlined in red bc we're not targeting the right ecmascript or smth? It's probably either a small fix to a config file or you could honestly just remove the getters and directly access the controller state, we have way too many unnecessary methods in these sandboxes anyway
- in the resultlist, the `getDate` method has a squiggly underline where you try to access the date of each result. I'm 99% sure that's a default field that will aways exist so you can probably just add an exclamation point after it so it won't complain that it's undefined. Relatedly, I'm not sure why we're rendering the date separately from the result- you should probably move that into the resultlink component so that the entire thing is clickable
- less important than all the rest, but could we change the theme colors to match our current branding? you should just have to change the theme.tsx file and most things should adjust themselves, and it's probably a good thing to do before the first major version

If any of this is unclear (quite possible since I can't comment directly on the files) feel free to ping me for a more in-depth explanation :) but it's all tiny changes so I'm approving now, let me know if you think you change anything substantially enough to warrant a second review

**Pull request merged**
